### PR TITLE
Add formatting, linting, and automated worker deploys

### PR DESCRIPTION
**Pull request by carterworks**
This adds [biomejs](https://biomejs.dev/) to the project. It is an alternative to Prettier and ESlint. I like it because it is much, much easier to configure and is very fast. 

There are ~~3~~ 4 npm new scripts:

- `lint`
- `format`
- `check` (which is a combination of lint and format),
- `cf-init-local-db`, which sets up the local d1 instance so that all things work when you run `npm run dev`

There is also the infrastructure to run both the linting and the formatting on the staged files before every commit, via [lefthook](https://github.com/evilmartians/lefthook).

This PR also adds automatic deployment. Whenever you merge to `master`, the GitHub Action will automatically deploy the worker. You just need to add a Cloudflare API token as a repo secret. See [the Cloudflare documentation](https://developers.cloudflare.com/workers/wrangler/ci-cd/#api-token) for instructions on how and where to generate a token. Call it `CLOUDFLARE_API_TOKEN`.

### CODE REVIEW

**Comment by catskull** [comment]
Woot! This is awesome. I just added the api key so let's see if this works!

**Comment by catskull** [comment]
it worked!
https://github.com/catskull/replies/actions/runs/10907603934/job/30271660406

**Comment by catskull** [comment]
@carterworks what is the difference between linting and formatting?

Also how do I run those commands?

**Comment by carterworks** [comment]
> @carterworks what is the difference between linting and formatting?

Formatting: tabs vs spaces, consistent alignment, spacing, etc. Visual only.
Linting: making sure rules are being formatted, like "don't use var" or "prefer template strings" or "don't use for..in". We apply all the [rules in Biome's "recommended" ruleset](https://biomejs.dev/linter/rules/), except for the "don't use forEach" rule. For most rules, it will apply a fix automatically.

You can run the formatter by `npm run format`, the linting `npm run lint` and you can run both at the same time with `npm run check`. They will also run both run whenever you commit files.

**Comment by catskull** [comment]
I just sent this PR as a reference to a friend seeking JS tooling examples. I think it's a great example!

**Pull request merged**
